#!/usr/bin/env python
import pandas as pd
import sys
import code
pd.set_option('max_columns', 10)
pd.set_option("max_rows", 100)
pd.set_option('display.width', 100)

def load_data(fp):
    if ".csv" in fp:
        df = pd.read_csv(fp)
    elif ".xlsx" in fp:
        df = pd.read_excel(fp, sheet_name=None)
    elif ".h5" in fp:
        df = pd.read_hdf(fp)
    elif ".parquet" in fp:
        df = pd.read_parquet(fp)
    else:
        raise Exception("unknown file type {x}".format(x=fp))
    return df

if __name__ == '__main__':
    fp = sys.argv[1]
    df = load_data(fp)
    code.interact(local=locals())
